name: Build/release

on:
  push:
    branches:
      - "master"

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ join(steps.version.outputs.*, '\n') }}

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12

      - name: "Automated Version Bump"
        id: version
        uses: "phips28/gh-action-bump-version@master"
        with:
          patch-wording: 'patch'
          tag-prefix: ''
          skip-tag: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "print"
        run: echo "version bump is ${{ join(steps.version.outputs.*, '\n') }}"


  create-release:
    needs: bump-version
    runs-on: ${{ matrix.os }}

    if: ${{ !!needs.bump-version.outputs.version }}

    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          release: ${{ !!needs.bump-version.outputs.version }}

          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

  release-draft:
    runs-on: ubuntu-latest
    if: ${{ !!needs.bump-version.outputs.version }}
    needs: [ bump-version,create-release ]
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Publish release on GitHub
        uses: test-room-7/action-publish-release-drafts@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag-name: ${{ steps.package-version.outputs.current-version }}
